### ISSUE TITLE
Robocopy error depending on Working Directory

### ISSUE THREAD

**Issue by aaronmrqz1** [EliteLoser/GetSTFolderSize#11] opened 2023-04-11 20:37 UTC
Specifically in this piece of code, you use "NULL" as destination and errors out depending on Working Directory being used.
I get this error if my working directory is "C:\Windows\System32" (Default when opening PS as admin) and "C:\users\myUserID" (Default when opening PS as regular user), but works just fine if first I switch directories to "C:\Temp" or "C:\users\myUserID\Downloads". Unsure of why some working directories will work and why others won't. I suspect it is a permissions issue (Work laptop being used). 
Might be worth swapping out the "NULL" to "C:\Temp" or adding additional code to swap as needed for better support for all users. If I replace "NULL", it doesn't seem to matter what my Working Directory path is and works as expected.

Code:
[String] $Summary = robocopy $p NULL $RoboCopyArgs | Select-Object -Last 8

Function warning:
"WARNING: Path 'C:\windows\system32' output from robocopy was not in an expected format."

Robocopy outside of this function I see the following error:
"2023/04/11 13:12:16 ERROR 123 (0x0000007B) Accessing Destination Directory C:\windows\system32\NULL\
The filename, directory name, or volume label syntax is incorrect."

**Comment by EliteLoser** [comment] 2023-04-12 17:30
Interesting. I haven't used this code in a while myself (different tasks at work).

I think I have a good solution in using ```$Env:Temp``` instead of "NULL". I also suspect it's related to permissions in the working directory based on your research. Intuitively, I expect using $Env:Temp to work. It is usually some profile\AppData\ folder where you have permissions to write. It seems the implementation of robocopy somehow tries to create the folder (guess) or performs some type of check against the filesystem path and needs it writable.

Thank you for bothering to provide feedback - the world now owes you a coffee/beer/tea!

I will make a branch and put $Env:Temp there, instead of NULL, then I will test and merge into main if it works. If it doesn't work, I will at least provide a better error message somehow when this happens (but hopefully it works).

**Comment by EliteLoser** [comment] 2023-04-12 17:40
@aaronmrqz1 can you try this one and see if it works better? If not, I will try to get it tested later myself.. Using Linux at the moment. https://github.com/EliteLoser/GetSTFolderSize/blob/working-dir-bug/GetSTFolderSize.psm1

**Comment by EliteLoser** [comment] 2023-04-12 18:11
I tested both version 1.3.1 and the 1.3.2 in the working-dir-bug branch from C:\Windows\system32 with -RoboOnly against some folders. They both work for me. I am unable to reproduce your issue, but this version might solve your problems. Can you confirm? I suspect it depends on your version of robocopy.exe. @aaronmrqz1

**Comment by aaronmrqz1** [comment] 2023-04-14 01:20
@EliteLoser Thanks for taking the time. Yes it works perfectly on my machine now, regardless of working directory used. It has to be related to permissions. Even as an Admin, a lot of hoops I have to go through with all the restrictions in place. My situation might be unique, but hopefully anyone else in my position won't run into that issue going forward now. Great function!

**Comment by EliteLoser** [comment] 2023-04-14 15:40
Great, thanks for letting me know. I merged in the small change in pull request #12 . Closing this.

**Closed as completed by EliteLoser** 2023-04-14 15:40 UTC
Labels: bug, enhancement
